### ISSUE TITLE
KZColorPicker wont build on XCode 4.6.3

### ISSUE THREAD

**Issue by jdcrunchman** [alexrestrepo/KZColorPicker#4]
When I run the program,    I get...

Use of Undeclared Identifier IS_IPAD on line 30 of file "CMQGDefaultColorViewController.m".

Can you help me with this?

John
